/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'text-primary':              '#f0f0f0',
        'text-secondary':            '#a0a0b0',
        'text-tertiary':             '#606070',
        'surface':                   '#171214',
        'background':                '#171214',
        'surface-dim':               '#171214',
        'surface-container':         '#241e20',
        'surface-container-low':     '#201a1c',
        'surface-container-high':    '#2f282a',
        'surface-container-highest': '#3a3335',
        'surface-variant':           '#3a3335',
        'on-surface':                '#ece0e2',
        'on-surface-variant':        '#bacac5',
        'on-background':             '#ece0e2',
        'primary':                   '#58f5df',
        'primary-container':         '#2ed8c3',
        'primary-fixed':             '#5ffae4',
        'primary-fixed-dim':         '#37ddc8',
        'on-primary':                '#003731',
        'on-primary-fixed':          '#00201c',
        'on-primary-container':      '#005a50',
        'secondary':                 '#c0c1ff',
        'secondary-container':       '#2e31b9',
        'on-secondary':              '#0f09a4',
        'on-secondary-container':    '#abaeff',
        'tertiary':                  '#edd4ff',
        'tertiary-container':        '#dab1ff',
        'on-tertiary':               '#490080',
        'status-red':                '#ef4444',
        'status-amber':              '#f59e0b',
        'error':                     '#ffb4ab',
        'error-container':           '#93000a',
        'border-subtle':             'rgba(255, 255, 255, 0.07)',
        'border-hover':              'rgba(255, 255, 255, 0.14)',
        'surface-card':              'rgba(255, 255, 255, 0.02)',
        'surface-tint':              '#37ddc8',
        'outline':                   '#859490',
        'outline-variant':           '#3b4a46',
        'inverse-surface':           '#ece0e2',
        'inverse-on-surface':        '#352f31',
        'inverse-primary':           '#006b5f',
      },
      fontFamily: {
        'label-mono':         ['JetBrains Mono', 'monospace'],
        'label-caps':         ['Outfit', 'sans-serif'],
        'display-lg':         ['Playfair Display', 'serif'],
        'display-lg-mobile':  ['Playfair Display', 'serif'],
        'body-md':            ['Outfit', 'sans-serif'],
        'body-sm':            ['Outfit', 'sans-serif'],
        'body-lg':            ['Outfit', 'sans-serif'],
        'headline-md':        ['Playfair Display', 'serif'],
        'headline-sm':        ['Playfair Display', 'serif'],
        display:              ['Playfair Display', 'serif'],
        sans:                 ['Outfit', 'sans-serif'],
        mono:                 ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'label-mono':         ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-caps':         ['11px', { lineHeight: '1.0', letterSpacing: '0.1em',  fontWeight: '600' }],
        'display-lg-mobile':  ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-lg':         ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md':            ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm':            ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg':            ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md':        ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-sm':        ['24px', { lineHeight: '1.3', fontWeight: '600' }],
      },
      spacing: {
        'margin-mobile':  '16px',
        'margin-desktop': '40px',
        'gutter': '1.5rem',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
      animation: {
        'fade-up':    'fadeUp 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in':    'fadeIn 0.5s ease-out forwards',
        'float':      'float 6s ease-in-out infinite',
        'glow':       'glowPulse 3s ease-in-out infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeUp:    { '0%': { opacity: '0', transform: 'translateY(24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        fadeIn:    { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        float:     { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        glowPulse: { '0%, 100%': { boxShadow: '0 0 15px rgba(46,216,195,0.15)' }, '50%': { boxShadow: '0 0 35px rgba(46,216,195,0.4)' } },
      },
    },
  },
  plugins: [
    function({ addUtilities }) {
      addUtilities({
        '.pb-safe': { paddingBottom: 'env(safe-area-inset-bottom, 0px)' },
        '.pt-safe': { paddingTop:    'env(safe-area-inset-top, 0px)' },
      })
    },
  ],
}
